<a href="https://colab.research.google.com/github/mubinui/DeepLearning/blob/main/Copy_of_NecessaryMaths.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Derivatives
Slope: For linear equations, a constant
$$ Slope =  \frac {Δy} {\Delta {x}}$$

Derivatives for non-linear equations , a function 
$$ \frac {d} {dx} {(x)} $$

Partial derivatives
 if ,$$ f(x, y) = x^3 + y^3 $$
 The partial derivatives will be 
 $$ \frac {δf} {δx} {=3x^2+0 = 3x^2}$$ </br>
$$ \frac {δf} {δy} {=0+3y^2 = 3y^2}$$
Significance of the two equations 

**How much the function is changing due to the change in x**</br>
**How much the function is changing due to the change in y** </br>
Derivatives uses for adjusting weight and back propagarion in neural network







#Matrix Manipulation
Dot product =  row $\times$ column 
$$ Dot Product = \sum _{i=0}^{n}{row \times {column}}$$


In [ ]:
import numpy as np 

In [ ]:
rev = np.array([[180, 200, 100], [20, 30, 40], [12, 24, 26]])
exp = np.array([[10, 20, 30], [10, 15, 20], [25, 30, 35]])

In [ ]:
profit = rev-exp
print(profit)

[[170 180  70]
 [ 10  15  20]
 [-13  -6  -9]]


In [ ]:
yr_2028 = [30, 40, 10] # prodA , prodB , prodC
yr_2029 = [10, 40, 50]
yr_2030 = [50, 60, 70]
unit_sold = np.array([yr_2028, yr_2029, yr_2030])
price_per_unit = np.array([40, 50, 60])
total_rev_per_yr = np.dot(price_per_unit, unit_sold)
print(total_rev_per_yr)

[4700 7200 7100]
